# Generated by Django 4.2.7 on 2025-07-13 03:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distribution_type", models.CharField(max_length=50)),
                ("parameters", models.JSONField()),
                ("probabilities", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WindData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "netcdf_file",
                    models.FileField(
                        upload_to="netcdf_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["nc"]
                            )
                        ],
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TurbineResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turbine_type", models.CharField(max_length=50)),
                ("total_energy", models.FloatField()),
                ("max_energy", models.FloatField()),
                ("load_factor", models.FloatField()),
                ("energy_distribution", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.analysisresult",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="wind_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analysis.winddata"
            ),
        ),
    ]
