# Generated by Django 4.2.7 on 2025-07-13 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="winddata",
            name="year_analyzed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TurbineAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turbine_type", models.CharField(max_length=50)),
                ("distribution_used", models.CharField(max_length=20)),
                ("energy_distribution", models.JSONField()),
                ("total_energy", models.FloatField()),
                ("max_energy", models.FloatField()),
                ("load_factor", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wind_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.winddata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DistributionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distribution_type", models.CharField(max_length=20)),
                ("parameters", models.JSONField()),
                ("aic", models.FloatField()),
                ("chi_square", models.FloatField()),
                ("ks_test", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wind_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.winddata",
                    ),
                ),
            ],
        ),
    ]
