# Generated by Django 4.2.7 on 2025-07-13 11:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_winddata_year_analyzed_turbineanalysis_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysisresult",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Analysis Result",
                "verbose_name_plural": "Analysis Results",
            },
        ),
        migrations.AlterModelOptions(
            name="distributionresult",
            options={
                "ordering": ["aic"],
                "verbose_name": "Distribution Result",
                "verbose_name_plural": "Distribution Results",
            },
        ),
        migrations.AlterModelOptions(
            name="turbineanalysis",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Turbine Analysis",
                "verbose_name_plural": "Turbine Analyses",
            },
        ),
        migrations.AlterModelOptions(
            name="turbineresult",
            options={
                "ordering": ["turbine_type"],
                "verbose_name": "Turbine Result",
                "verbose_name_plural": "Turbine Results",
            },
        ),
        migrations.AlterModelOptions(
            name="winddata",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Wind Data",
                "verbose_name_plural": "Wind Data",
            },
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="distribution_type",
            field=models.CharField(
                help_text="Type of distribution used (e.g., Weibull, Normal)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="parameters",
            field=models.JSONField(
                default=dict, help_text="Parameters of the fitted distribution"
            ),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="probabilities",
            field=models.JSONField(
                default=dict, help_text="Wind speed probabilities by bin"
            ),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="wind_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_results",
                to="analysis.winddata",
            ),
        ),
        migrations.AlterField(
            model_name="distributionresult",
            name="aic",
            field=models.FloatField(help_text="Akaike Information Criterion value"),
        ),
        migrations.AlterField(
            model_name="distributionresult",
            name="chi_square",
            field=models.FloatField(help_text="Chi-square goodness-of-fit statistic"),
        ),
        migrations.AlterField(
            model_name="distributionresult",
            name="distribution_type",
            field=models.CharField(
                help_text="Statistical distribution type", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="distributionresult",
            name="ks_test",
            field=models.FloatField(help_text="Kolmogorov-Smirnov test p-value"),
        ),
        migrations.AlterField(
            model_name="distributionresult",
            name="parameters",
            field=models.JSONField(
                default=dict, help_text="Fitted parameters for the distribution"
            ),
        ),
        migrations.AlterField(
            model_name="distributionresult",
            name="wind_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distribution_results",
                to="analysis.winddata",
            ),
        ),
        migrations.AlterField(
            model_name="turbineanalysis",
            name="distribution_used",
            field=models.CharField(
                help_text="Wind distribution model used", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="turbineanalysis",
            name="energy_distribution",
            field=models.JSONField(
                default=list, help_text="Energy production by wind speed bin"
            ),
        ),
        migrations.AlterField(
            model_name="turbineanalysis",
            name="load_factor",
            field=models.FloatField(help_text="Capacity factor percentage"),
        ),
        migrations.AlterField(
            model_name="turbineanalysis",
            name="max_energy",
            field=models.FloatField(help_text="Maximum possible annual energy in kWh"),
        ),
        migrations.AlterField(
            model_name="turbineanalysis",
            name="total_energy",
            field=models.FloatField(help_text="Total annual energy production in kWh"),
        ),
        migrations.AlterField(
            model_name="turbineanalysis",
            name="turbine_type",
            field=models.CharField(
                help_text="Type of wind turbine analyzed", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="turbineanalysis",
            name="wind_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turbine_analyses",
                to="analysis.winddata",
            ),
        ),
        migrations.AlterField(
            model_name="turbineresult",
            name="analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turbine_results",
                to="analysis.analysisresult",
            ),
        ),
        migrations.AlterField(
            model_name="turbineresult",
            name="energy_distribution",
            field=models.JSONField(
                default=list, help_text="Energy output distribution by wind speed bin"
            ),
        ),
        migrations.AlterField(
            model_name="turbineresult",
            name="load_factor",
            field=models.FloatField(help_text="Capacity factor as percentage (0-100)"),
        ),
        migrations.AlterField(
            model_name="turbineresult",
            name="max_energy",
            field=models.FloatField(
                help_text="Maximum possible annual energy output in kWh"
            ),
        ),
        migrations.AlterField(
            model_name="turbineresult",
            name="total_energy",
            field=models.FloatField(help_text="Total annual energy output in kWh"),
        ),
        migrations.AlterField(
            model_name="turbineresult",
            name="turbine_type",
            field=models.CharField(
                help_text="Type of wind turbine used in calculation", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="winddata",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="End time of the data collection period",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="winddata",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="Latitude coordinate of the data location",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="winddata",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="Longitude coordinate of the data location",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="winddata",
            name="name",
            field=models.CharField(
                help_text="Descriptive name for the wind data", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="winddata",
            name="netcdf_file",
            field=models.FileField(
                help_text="Upload NetCDF file containing wind data",
                upload_to="netcdf_files",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["nc"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="winddata",
            name="start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Start time of the data collection period",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="winddata",
            name="year_analyzed",
            field=models.IntegerField(
                blank=True,
                help_text="Year the data was collected",
                null=True,
                validators=[django.core.validators.MinValueValidator(1900)],
            ),
        ),
    ]
