# Generated by Django 4.2.7 on 2025-07-13 11:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_alter_analysisresult_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turbineanalysis",
            name="wind_data",
        ),
        migrations.AlterModelOptions(
            name="analysisresult",
            options={},
        ),
        migrations.AlterModelOptions(
            name="turbineresult",
            options={},
        ),
        migrations.AlterModelOptions(
            name="winddata",
            options={},
        ),
        migrations.RemoveField(
            model_name="winddata",
            name="year_analyzed",
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="distribution_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="parameters",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="probabilities",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="analysisresult",
            name="wind_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analysis.winddata"
            ),
        ),
        migrations.AlterField(
            model_name="turbineresult",
            name="analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analysis.analysisresult",
            ),
        ),
        migrations.AlterField(
            model_name="turbineresult",
            name="energy_distribution",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="turbineresult",
            name="load_factor",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="turbineresult",
            name="max_energy",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="turbineresult",
            name="total_energy",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="turbineresult",
            name="turbine_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="winddata",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="winddata",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="winddata",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="winddata",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="winddata",
            name="netcdf_file",
            field=models.FileField(
                upload_to="netcdf_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["nc"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="winddata",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="DistributionResult",
        ),
        migrations.DeleteModel(
            name="TurbineAnalysis",
        ),
    ]
