# Generated by Django 4.2.7 on 2025-07-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_remove_turbineanalysis_wind_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WindDataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="wind_data/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("original_name", models.CharField(max_length=255)),
            ],
        ),
    ]
