# Generated by Django 4.2.7 on 2025-07-13 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0005_winddatafile"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distribution_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("lognormal", "Lognormal"),
                            ("weibull", "Weibull"),
                            ("gumbel", "Gumbel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EnergyAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turbine_type",
                    models.CharField(
                        choices=[
                            ("bergey_excel_10", "Bergey Excel 10"),
                            ("bergey_excel_15", "Bergey Excel 15"),
                            ("cf_20", "CF 20"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_energy", models.FloatField()),
                ("max_energy", models.FloatField()),
                ("load_factor", models.FloatField()),
                ("energy_distribution", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "distribution_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.distributionanalysis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WindAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("wind_speeds", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="turbineresult",
            name="analysis",
        ),
        migrations.AddField(
            model_name="winddatafile",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="winddatafile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="winddatafile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="winddatafile",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="AnalysisResult",
        ),
        migrations.DeleteModel(
            name="TurbineResult",
        ),
        migrations.DeleteModel(
            name="WindData",
        ),
        migrations.AddField(
            model_name="windanalysis",
            name="wind_data",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analysis.winddatafile"
            ),
        ),
        migrations.AddField(
            model_name="distributionanalysis",
            name="wind_analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analysis.windanalysis"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="windanalysis",
            unique_together={("wind_data", "year")},
        ),
    ]
